default:  fxctmp9_tmp\SDK_Bloom_ps20.inc shaders\fxc\SDK_Bloom_ps20.vcs fxctmp9_tmp\SDK_Bloom_ps20b.inc shaders\fxc\SDK_Bloom_ps20b.vcs fxctmp9_tmp\SDK_screenspaceeffect_vs20.inc shaders\fxc\SDK_screenspaceeffect_vs20.vcs fxctmp9_tmp\SDK_bloomadd_ps20.inc shaders\fxc\SDK_bloomadd_ps20.vcs fxctmp9_tmp\SDK_bloomadd_ps20b.inc shaders\fxc\SDK_bloomadd_ps20b.vcs fxctmp9_tmp\Post_dof_ps20.inc shaders\fxc\Post_dof_ps20.vcs fxctmp9_tmp\Post_blur_ps20.inc shaders\fxc\Post_blur_ps20.vcs

fxctmp9_tmp\SDK_Bloom_ps20.inc shaders\fxc\SDK_Bloom_ps20.vcs: SDK_Bloom_ps2x.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" SDK_Bloom_ps2x.fxc-----SDK_Bloom_ps20
	echo SDK_Bloom_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_Bloom_ps20b.inc shaders\fxc\SDK_Bloom_ps20b.vcs: SDK_Bloom_ps2x.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" SDK_Bloom_ps2x.fxc-----SDK_Bloom_ps20b
	echo SDK_Bloom_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_screenspaceeffect_vs20.inc shaders\fxc\SDK_screenspaceeffect_vs20.vcs: SDK_screenspaceeffect_vs20.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_vs_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" SDK_screenspaceeffect_vs20.fxc-----SDK_screenspaceeffect_vs20
	echo SDK_screenspaceeffect_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_bloomadd_ps20.inc shaders\fxc\SDK_bloomadd_ps20.vcs: SDK_bloomadd_ps2x.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" SDK_bloomadd_ps2x.fxc-----SDK_bloomadd_ps20
	echo SDK_bloomadd_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_bloomadd_ps20b.inc shaders\fxc\SDK_bloomadd_ps20b.vcs: SDK_bloomadd_ps2x.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" SDK_bloomadd_ps2x.fxc-----SDK_bloomadd_ps20b
	echo SDK_bloomadd_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\Post_dof_ps20.inc shaders\fxc\Post_dof_ps20.vcs: Post_dof_ps20.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" Post_dof_ps20.fxc-----Post_dof_ps20
	echo Post_dof_ps20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\Post_blur_ps20.inc shaders\fxc\Post_blur_ps20.vcs: Post_blur_ps20.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl G:\programming\jurassic-life-2013\jurassic-life\sp\src\devtools\bin\fxc_prep.pl   -source "G:\programming\jurassic-life-2013\jurassic-life\sp\src" Post_blur_ps20.fxc-----Post_blur_ps20
	echo Post_blur_ps20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

